services:
  document-rag:
    build: .
    container_name: document-rag

    ports:
      - "8888:8888"
      - "5500:5500"

    volumes:
      - .:/workspace

    environment:
      - PYTHONUNBUFFERED=1
